unclespace_ver3/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using unclespace_ver3.Models;

namespace unclespace_ver3.Controllers
{
    public class CatalogController : Controller
    {
        public ActionResult Index()
        {
            List<Product> products;
            List<ProductVsImage> purchases = new List<ProductVsImage>();

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                products = db.Products.Include(p => p.Category).ToList();
            }

            foreach (var p in products)
            {
                purchases.Add(new ProductVsImage(p));
            }

            return View(purchases);
        }
    }
}

unclespace_ver3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Каталог", "Index", "Catalog")</li>
                    <li>@Html.ActionLink("Администратор", "Index", "Admin")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery.validate.min.js")
    @Scripts.Render("~/scripts/jquery-1.10.2.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)
</body>
</html>